server:
  port: 80

jwt:
  secret: javainuse

spring:
  data:
    mongodb:
      user:
      password:
      uri: mongodb://localhost:27017/survey

  mail:
    host: smtp.gmail.com
    port: 587
    username: vinayak.jog.channel@gmail.com
    password: Anjali*17
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true